'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
'
Namespace CoL
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CASWebServiceSoapBinding", [Namespace]:="urn:spice"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Relationship)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Item)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Taxon)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(GSDInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SynonymWithRefs)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Place)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CommonNameWithRefs)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(StatusRef)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SpeciesName))>  _
    Partial Public Class CASWebServiceService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private webServiceTestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private satisfyType0RequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private satisfyType1RequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private type1WrapperTestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private satisfyType2RequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private satisfyType3RequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private satisfyType4RequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private satisfyType5RequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getHubIdentifiersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getCrossMapMatchesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApplication1.My.MySettings.Default.WindowsApplication1_CoL_CASWebServiceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event webServiceTestCompleted As webServiceTestCompletedEventHandler
        
        '''<remarks/>
        Public Event satisfyType0RequestCompleted As satisfyType0RequestCompletedEventHandler
        
        '''<remarks/>
        Public Event satisfyType1RequestCompleted As satisfyType1RequestCompletedEventHandler
        
        '''<remarks/>
        Public Event type1WrapperTestCompleted As type1WrapperTestCompletedEventHandler
        
        '''<remarks/>
        Public Event satisfyType2RequestCompleted As satisfyType2RequestCompletedEventHandler
        
        '''<remarks/>
        Public Event satisfyType3RequestCompleted As satisfyType3RequestCompletedEventHandler
        
        '''<remarks/>
        Public Event satisfyType4RequestCompleted As satisfyType4RequestCompletedEventHandler
        
        '''<remarks/>
        Public Event satisfyType5RequestCompleted As satisfyType5RequestCompletedEventHandler
        
        '''<remarks/>
        Public Event getHubIdentifiersCompleted As getHubIdentifiersCompletedEventHandler
        
        '''<remarks/>
        Public Event getCrossMapMatchesCompleted As getCrossMapMatchesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function webServiceTest() As <System.Xml.Serialization.SoapElementAttribute("webServiceTestReturn")> String
            Dim results() As Object = Me.Invoke("webServiceTest", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub webServiceTestAsync()
            Me.webServiceTestAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub webServiceTestAsync(ByVal userState As Object)
            If (Me.webServiceTestOperationCompleted Is Nothing) Then
                Me.webServiceTestOperationCompleted = AddressOf Me.OnwebServiceTestOperationCompleted
            End If
            Me.InvokeAsync("webServiceTest", New Object(-1) {}, Me.webServiceTestOperationCompleted, userState)
        End Sub
        
        Private Sub OnwebServiceTestOperationCompleted(ByVal arg As Object)
            If (Not (Me.webServiceTestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent webServiceTestCompleted(Me, New webServiceTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function satisfyType0Request() As <System.Xml.Serialization.SoapElementAttribute("satisfyType0RequestReturn")> String
            Dim results() As Object = Me.Invoke("satisfyType0Request", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub satisfyType0RequestAsync()
            Me.satisfyType0RequestAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub satisfyType0RequestAsync(ByVal userState As Object)
            If (Me.satisfyType0RequestOperationCompleted Is Nothing) Then
                Me.satisfyType0RequestOperationCompleted = AddressOf Me.OnsatisfyType0RequestOperationCompleted
            End If
            Me.InvokeAsync("satisfyType0Request", New Object(-1) {}, Me.satisfyType0RequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnsatisfyType0RequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.satisfyType0RequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent satisfyType0RequestCompleted(Me, New satisfyType0RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function satisfyType1Request(ByVal in0 As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN")> ByVal in1 As String, ByVal in2 As SearchLimit, ByVal in3 As String, ByVal in4 As Boolean) As <System.Xml.Serialization.SoapElementAttribute("satisfyType1RequestReturn")> Type1Results
            Dim results() As Object = Me.Invoke("satisfyType1Request", New Object() {in0, in1, in2, in3, in4})
            Return CType(results(0),Type1Results)
        End Function
        
        '''<remarks/>
        Public Overloads Sub satisfyType1RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As SearchLimit, ByVal in3 As String, ByVal in4 As Boolean)
            Me.satisfyType1RequestAsync(in0, in1, in2, in3, in4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub satisfyType1RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As SearchLimit, ByVal in3 As String, ByVal in4 As Boolean, ByVal userState As Object)
            If (Me.satisfyType1RequestOperationCompleted Is Nothing) Then
                Me.satisfyType1RequestOperationCompleted = AddressOf Me.OnsatisfyType1RequestOperationCompleted
            End If
            Me.InvokeAsync("satisfyType1Request", New Object() {in0, in1, in2, in3, in4}, Me.satisfyType1RequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnsatisfyType1RequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.satisfyType1RequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent satisfyType1RequestCompleted(Me, New satisfyType1RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function type1WrapperTest(ByVal in0 As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN")> ByVal in1 As String, ByVal in2 As SearchLimit, ByVal in3 As String, ByVal in4 As Boolean) As <System.Xml.Serialization.SoapElementAttribute("type1WrapperTestReturn")> Type1Results
            Dim results() As Object = Me.Invoke("type1WrapperTest", New Object() {in0, in1, in2, in3, in4})
            Return CType(results(0),Type1Results)
        End Function
        
        '''<remarks/>
        Public Overloads Sub type1WrapperTestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As SearchLimit, ByVal in3 As String, ByVal in4 As Boolean)
            Me.type1WrapperTestAsync(in0, in1, in2, in3, in4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub type1WrapperTestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As SearchLimit, ByVal in3 As String, ByVal in4 As Boolean, ByVal userState As Object)
            If (Me.type1WrapperTestOperationCompleted Is Nothing) Then
                Me.type1WrapperTestOperationCompleted = AddressOf Me.Ontype1WrapperTestOperationCompleted
            End If
            Me.InvokeAsync("type1WrapperTest", New Object() {in0, in1, in2, in3, in4}, Me.type1WrapperTestOperationCompleted, userState)
        End Sub
        
        Private Sub Ontype1WrapperTestOperationCompleted(ByVal arg As Object)
            If (Not (Me.type1WrapperTestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent type1WrapperTestCompleted(Me, New type1WrapperTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function satisfyType2Request(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Boolean) As <System.Xml.Serialization.SoapElementAttribute("satisfyType2RequestReturn")> StandardData
            Dim results() As Object = Me.Invoke("satisfyType2Request", New Object() {in0, in1, in2, in3})
            Return CType(results(0),StandardData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub satisfyType2RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Boolean)
            Me.satisfyType2RequestAsync(in0, in1, in2, in3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub satisfyType2RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Boolean, ByVal userState As Object)
            If (Me.satisfyType2RequestOperationCompleted Is Nothing) Then
                Me.satisfyType2RequestOperationCompleted = AddressOf Me.OnsatisfyType2RequestOperationCompleted
            End If
            Me.InvokeAsync("satisfyType2Request", New Object() {in0, in1, in2, in3}, Me.satisfyType2RequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnsatisfyType2RequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.satisfyType2RequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent satisfyType2RequestCompleted(Me, New satisfyType2RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function satisfyType3Request(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Boolean) As <System.Xml.Serialization.SoapElementAttribute("satisfyType3RequestReturn")> GSDInfo()
            Dim results() As Object = Me.Invoke("satisfyType3Request", New Object() {in0, in1, in2})
            Return CType(results(0),GSDInfo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub satisfyType3RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Boolean)
            Me.satisfyType3RequestAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub satisfyType3RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As Boolean, ByVal userState As Object)
            If (Me.satisfyType3RequestOperationCompleted Is Nothing) Then
                Me.satisfyType3RequestOperationCompleted = AddressOf Me.OnsatisfyType3RequestOperationCompleted
            End If
            Me.InvokeAsync("satisfyType3Request", New Object() {in0, in1, in2}, Me.satisfyType3RequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnsatisfyType3RequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.satisfyType3RequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent satisfyType3RequestCompleted(Me, New satisfyType3RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function satisfyType4Request(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Boolean) As <System.Xml.Serialization.SoapElementAttribute("satisfyType4RequestReturn")> Taxon()
            Dim results() As Object = Me.Invoke("satisfyType4Request", New Object() {in0, in1, in2, in3})
            Return CType(results(0),Taxon())
        End Function
        
        '''<remarks/>
        Public Overloads Sub satisfyType4RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Boolean)
            Me.satisfyType4RequestAsync(in0, in1, in2, in3, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub satisfyType4RequestAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal in3 As Boolean, ByVal userState As Object)
            If (Me.satisfyType4RequestOperationCompleted Is Nothing) Then
                Me.satisfyType4RequestOperationCompleted = AddressOf Me.OnsatisfyType4RequestOperationCompleted
            End If
            Me.InvokeAsync("satisfyType4Request", New Object() {in0, in1, in2, in3}, Me.satisfyType4RequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnsatisfyType4RequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.satisfyType4RequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent satisfyType4RequestCompleted(Me, New satisfyType4RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function satisfyType5Request(ByVal in0 As String, ByVal in1 As SearchLimit, ByVal in2 As String, ByVal in3 As String, ByVal in4 As Boolean) As <System.Xml.Serialization.SoapElementAttribute("satisfyType5RequestReturn")> Taxon()
            Dim results() As Object = Me.Invoke("satisfyType5Request", New Object() {in0, in1, in2, in3, in4})
            Return CType(results(0),Taxon())
        End Function
        
        '''<remarks/>
        Public Overloads Sub satisfyType5RequestAsync(ByVal in0 As String, ByVal in1 As SearchLimit, ByVal in2 As String, ByVal in3 As String, ByVal in4 As Boolean)
            Me.satisfyType5RequestAsync(in0, in1, in2, in3, in4, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub satisfyType5RequestAsync(ByVal in0 As String, ByVal in1 As SearchLimit, ByVal in2 As String, ByVal in3 As String, ByVal in4 As Boolean, ByVal userState As Object)
            If (Me.satisfyType5RequestOperationCompleted Is Nothing) Then
                Me.satisfyType5RequestOperationCompleted = AddressOf Me.OnsatisfyType5RequestOperationCompleted
            End If
            Me.InvokeAsync("satisfyType5Request", New Object() {in0, in1, in2, in3, in4}, Me.satisfyType5RequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnsatisfyType5RequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.satisfyType5RequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent satisfyType5RequestCompleted(Me, New satisfyType5RequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function getHubIdentifiers() As <System.Xml.Serialization.SoapElementAttribute("getHubIdentifiersResponse")> String()
            Dim results() As Object = Me.Invoke("getHubIdentifiers", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getHubIdentifiersAsync()
            Me.getHubIdentifiersAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getHubIdentifiersAsync(ByVal userState As Object)
            If (Me.getHubIdentifiersOperationCompleted Is Nothing) Then
                Me.getHubIdentifiersOperationCompleted = AddressOf Me.OngetHubIdentifiersOperationCompleted
            End If
            Me.InvokeAsync("getHubIdentifiers", New Object(-1) {}, Me.getHubIdentifiersOperationCompleted, userState)
        End Sub
        
        Private Sub OngetHubIdentifiersOperationCompleted(ByVal arg As Object)
            If (Not (Me.getHubIdentifiersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getHubIdentifiersCompleted(Me, New getHubIdentifiersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="urn:spice", ResponseNamespace:="urn:spice")>  _
        Public Function getCrossMapMatches(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String) As <System.Xml.Serialization.SoapElementAttribute("getCrossMapMatchesResponse")> CrossMap
            Dim results() As Object = Me.Invoke("getCrossMapMatches", New Object() {in0, in1, in2})
            Return CType(results(0),CrossMap)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getCrossMapMatchesAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String)
            Me.getCrossMapMatchesAsync(in0, in1, in2, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getCrossMapMatchesAsync(ByVal in0 As String, ByVal in1 As String, ByVal in2 As String, ByVal userState As Object)
            If (Me.getCrossMapMatchesOperationCompleted Is Nothing) Then
                Me.getCrossMapMatchesOperationCompleted = AddressOf Me.OngetCrossMapMatchesOperationCompleted
            End If
            Me.InvokeAsync("getCrossMapMatches", New Object() {in0, in1, in2}, Me.getCrossMapMatchesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetCrossMapMatchesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCrossMapMatchesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCrossMapMatchesCompleted(Me, New getCrossMapMatchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class SearchLimit
        
        Private gsdIdentifierField As String
        
        Private limitField As Integer
        
        Private skipField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gsdIdentifier() As String
            Get
                Return Me.gsdIdentifierField
            End Get
            Set
                Me.gsdIdentifierField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property limit() As Integer
            Get
                Return Me.limitField
            End Get
            Set
                Me.limitField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property skip() As Integer
            Get
                Return Me.skipField
            End Get
            Set
                Me.skipField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Relationship
        
        Private crossMapTaxonField As CrossMapTaxon
        
        Private relationshiptypeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property crossMapTaxon() As CrossMapTaxon
            Get
                Return Me.crossMapTaxonField
            End Get
            Set
                Me.crossMapTaxonField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute("relationship-type", IsNullable:=true)>  _
        Public Property relationshiptype() As String
            Get
                Return Me.relationshiptypeField
            End Get
            Set
                Me.relationshiptypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CrossMapTaxon
        
        Private crossMapNameField As CrossMapName
        
        Private listIdField As String
        
        Private taxonIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property crossMapName() As CrossMapName
            Get
                Return Me.crossMapNameField
            End Get
            Set
                Me.crossMapNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property listId() As String
            Get
                Return Me.listIdField
            End Get
            Set
                Me.listIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property taxonId() As String
            Get
                Return Me.taxonIdField
            End Get
            Set
                Me.taxonIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CrossMapName
        
        Private authorityField As String
        
        Private binomialField As Binomial
        
        Private higherTaxonNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property binomial() As Binomial
            Get
                Return Me.binomialField
            End Get
            Set
                Me.binomialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property higherTaxonName() As String
            Get
                Return Me.higherTaxonNameField
            End Get
            Set
                Me.higherTaxonNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Binomial
        
        Private genusField As String
        
        Private epithetField As String
        
        Private authorityField As String
        
        Private crossMapInfraSpecificPortionField As CrossMapInfraSpecificPortion
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property genus() As String
            Get
                Return Me.genusField
            End Get
            Set
                Me.genusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property epithet() As String
            Get
                Return Me.epithetField
            End Get
            Set
                Me.epithetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property crossMapInfraSpecificPortion() As CrossMapInfraSpecificPortion
            Get
                Return Me.crossMapInfraSpecificPortionField
            End Get
            Set
                Me.crossMapInfraSpecificPortionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CrossMapInfraSpecificPortion
        
        Private rankField As String
        
        Private infraspecificnameField As String
        
        Private authorityField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property rank() As String
            Get
                Return Me.rankField
            End Get
            Set
                Me.rankField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute("infraspecific-name", IsNullable:=true)>  _
        Public Property infraspecificname() As String
            Get
                Return Me.infraspecificnameField
            End Get
            Set
                Me.infraspecificnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Item
        
        Private crossMapTaxonField As CrossMapTaxon
        
        Private relationshipField() As Relationship
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property crossMapTaxon() As CrossMapTaxon
            Get
                Return Me.crossMapTaxonField
            End Get
            Set
                Me.crossMapTaxonField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property relationship() As Relationship()
            Get
                Return Me.relationshipField
            End Get
            Set
                Me.relationshipField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CrossMap
        
        Private itemField() As Item
        
        Private idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property item() As Item()
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Species
        
        Private identifierField As String
        
        Private sourceGSDField As String
        
        Private avcNameField As AVCName
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property sourceGSD() As String
            Get
                Return Me.sourceGSDField
            End Get
            Set
                Me.sourceGSDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property avcName() As AVCName
            Get
                Return Me.avcNameField
            End Get
            Set
                Me.avcNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class AVCName
        Inherits NameWithAVC
        
        Private nameField As Name
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property name() As Name
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN", IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.SoapIncludeAttribute(GetType(FullName)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Name
        
        Private nameTypeField As String
        
        Private fullNameField As FullName
        
        Private virusNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN", IsNullable:=true)>  _
        Public Property nameType() As String
            Get
                Return Me.nameTypeField
            End Get
            Set
                Me.nameTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property fullName() As FullName
            Get
                Return Me.fullNameField
            End Get
            Set
                Me.fullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property virusName() As String
            Get
                Return Me.virusNameField
            End Get
            Set
                Me.virusNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class FullName
        Inherits Name
        
        Private authorityField As String
        
        Private genusField As String
        
        Private specificEpithetField As String
        
        Private infraspecificPortionField As InfraSpecificPortion
        
        Private subgeneraField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property genus() As String
            Get
                Return Me.genusField
            End Get
            Set
                Me.genusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property specificEpithet() As String
            Get
                Return Me.specificEpithetField
            End Get
            Set
                Me.specificEpithetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property infraspecificPortion() As InfraSpecificPortion
            Get
                Return Me.infraspecificPortionField
            End Get
            Set
                Me.infraspecificPortionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property subgenera() As String
            Get
                Return Me.subgeneraField
            End Get
            Set
                Me.subgeneraField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class InfraSpecificPortion
        
        Private infraspecificMarkerField As String
        
        Private infraspecificEpithetField As String
        
        Private authorityField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property InfraspecificMarker() As String
            Get
                Return Me.infraspecificMarkerField
            End Get
            Set
                Me.infraspecificMarkerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property infraspecificEpithet() As String
            Get
                Return Me.infraspecificEpithetField
            End Get
            Set
                Me.infraspecificEpithetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.SoapIncludeAttribute(GetType(AVCName)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class NameWithAVC
        
        Private nameWithAVCTypeField As String
        
        Private avcNameField As AVCName
        
        Private synonymWithAVCField As SynonymWithAVC
        
        Private commonNameWithAVCField As CommonNameWithAVC
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN", IsNullable:=true)>  _
        Public Property nameWithAVCType() As String
            Get
                Return Me.nameWithAVCTypeField
            End Get
            Set
                Me.nameWithAVCTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property avcName() As AVCName
            Get
                Return Me.avcNameField
            End Get
            Set
                Me.avcNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property synonymWithAVC() As SynonymWithAVC
            Get
                Return Me.synonymWithAVCField
            End Get
            Set
                Me.synonymWithAVCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property commonNameWithAVC() As CommonNameWithAVC
            Get
                Return Me.commonNameWithAVCField
            End Get
            Set
                Me.commonNameWithAVCField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class SynonymWithAVC
        
        Private synonymField As Synonym
        
        Private aVCNameField As AVCName
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property synonym() As Synonym
            Get
                Return Me.synonymField
            End Get
            Set
                Me.synonymField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property AVCName() As AVCName
            Get
                Return Me.aVCNameField
            End Get
            Set
                Me.aVCNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Synonym
        
        Private nameField As Name
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property name() As Name
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN", IsNullable:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CommonNameWithAVC
        
        Private commonNameField As CommonName
        
        Private aVCNameField As AVCName
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property commonName() As CommonName
            Get
                Return Me.commonNameField
            End Get
            Set
                Me.commonNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property AVCName() As AVCName
            Get
                Return Me.aVCNameField
            End Get
            Set
                Me.aVCNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CommonName
        
        Private languageField As String
        
        Private placeNamesField() As String
        
        Private vernNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property placeNames() As String()
            Get
                Return Me.placeNamesField
            End Get
            Set
                Me.placeNamesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property vernName() As String
            Get
                Return Me.vernNameField
            End Get
            Set
                Me.vernNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class HigherTaxon
        
        Private identifierField As String
        
        Private sourceGSDField As String
        
        Private hasChildrenField As System.Nullable(Of Boolean)
        
        Private rankField As String
        
        Private taxonNameField As String
        
        Private authorityField As String
        
        Private viewField As String
        
        Private nameRefListField() As StatusRef
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property sourceGSD() As String
            Get
                Return Me.sourceGSDField
            End Get
            Set
                Me.sourceGSDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property hasChildren() As System.Nullable(Of Boolean)
            Get
                Return Me.hasChildrenField
            End Get
            Set
                Me.hasChildrenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property rank() As String
            Get
                Return Me.rankField
            End Get
            Set
                Me.rankField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property taxonName() As String
            Get
                Return Me.taxonNameField
            End Get
            Set
                Me.taxonNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property authority() As String
            Get
                Return Me.authorityField
            End Get
            Set
                Me.authorityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property view() As String
            Get
                Return Me.viewField
            End Get
            Set
                Me.viewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nameRefList() As StatusRef()
            Get
                Return Me.nameRefListField
            End Get
            Set
                Me.nameRefListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class StatusRef
        
        Private referenceField As Reference
        
        Private refTypeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property reference() As Reference
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN", IsNullable:=true)>  _
        Public Property refType() As String
            Get
                Return Me.refTypeField
            End Get
            Set
                Me.refTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Reference
        
        Private referenceTypeField As String
        
        Private litRefField As LitRef
        
        Private linkField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="NMTOKEN", IsNullable:=true)>  _
        Public Property referenceType() As String
            Get
                Return Me.referenceTypeField
            End Get
            Set
                Me.referenceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property litRef() As LitRef
            Get
                Return Me.litRefField
            End Get
            Set
                Me.litRefField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property link() As String
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class LitRef
        
        Private authorField As String
        
        Private yearField As Short
        
        Private titleField As String
        
        Private detailsField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property author() As String
            Get
                Return Me.authorField
            End Get
            Set
                Me.authorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property year() As Short
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property details() As String
            Get
                Return Me.detailsField
            End Get
            Set
                Me.detailsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Taxon
        
        Private higherTaxonField As HigherTaxon
        
        Private speciesField As Species
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property higherTaxon() As HigherTaxon
            Get
                Return Me.higherTaxonField
            End Get
            Set
                Me.higherTaxonField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property species() As Species
            Get
                Return Me.speciesField
            End Get
            Set
                Me.speciesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class GSDInfo
        
        Private contactLinkField As String
        
        Private dateField As [Date]
        
        Private descriptionField As String
        
        Private gsdIdentifierField As String
        
        Private gsdShortNameField As String
        
        Private gsdTitleField As String
        
        Private homeLinkField As String
        
        Private logoLinkField As String
        
        Private searchLinkField As String
        
        Private versionField As String
        
        Private viewField As String
        
        Private wrapperVersionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property contactLink() As String
            Get
                Return Me.contactLinkField
            End Get
            Set
                Me.contactLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property [date]() As [Date]
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gsdIdentifier() As String
            Get
                Return Me.gsdIdentifierField
            End Get
            Set
                Me.gsdIdentifierField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gsdShortName() As String
            Get
                Return Me.gsdShortNameField
            End Get
            Set
                Me.gsdShortNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gsdTitle() As String
            Get
                Return Me.gsdTitleField
            End Get
            Set
                Me.gsdTitleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property homeLink() As String
            Get
                Return Me.homeLinkField
            End Get
            Set
                Me.homeLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property logoLink() As String
            Get
                Return Me.logoLinkField
            End Get
            Set
                Me.logoLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property searchLink() As String
            Get
                Return Me.searchLinkField
            End Get
            Set
                Me.searchLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property view() As String
            Get
                Return Me.viewField
            End Get
            Set
                Me.viewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property wrapperVersion() As String
            Get
                Return Me.wrapperVersionField
            End Get
            Set
                Me.wrapperVersionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class [Date]
        
        Private dayField As Short
        
        Private monthField As Short
        
        Private yearField As Short
        
        '''<remarks/>
        Public Property day() As Short
            Get
                Return Me.dayField
            End Get
            Set
                Me.dayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property month() As Short
            Get
                Return Me.monthField
            End Get
            Set
                Me.monthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property year() As Short
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class SynonymWithRefs
        
        Private nameRefListField As NameRefList
        
        Private synonymField As Synonym
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nameRefList() As NameRefList
            Get
                Return Me.nameRefListField
            End Get
            Set
                Me.nameRefListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property synonym() As Synonym
            Get
                Return Me.synonymField
            End Get
            Set
                Me.synonymField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class NameRefList
        
        Private statusRefsField() As StatusRef
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property statusRefs() As StatusRef()
            Get
                Return Me.statusRefsField
            End Get
            Set
                Me.statusRefsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Scrutiny
        
        Private dateField As [Date]
        
        Private linkField As String
        
        Private personField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property [date]() As [Date]
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property link() As String
            Get
                Return Me.linkField
            End Get
            Set
                Me.linkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property person() As String
            Get
                Return Me.personField
            End Get
            Set
                Me.personField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Place
        
        Private occurrenceField As String
        
        Private placeNameField As String
        
        Private referenceField As Reference
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property occurrence() As String
            Get
                Return Me.occurrenceField
            End Get
            Set
                Me.occurrenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property placeName() As String
            Get
                Return Me.placeNameField
            End Get
            Set
                Me.placeNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property reference() As Reference
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Geography
        
        Private placesField() As Place
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property places() As Place()
            Get
                Return Me.placesField
            End Get
            Set
                Me.placesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class CommonNameWithRefs
        
        Private commonNameField As CommonName
        
        Private referencesField() As Reference
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property commonName() As CommonName
            Get
                Return Me.commonNameField
            End Get
            Set
                Me.commonNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property references() As Reference()
            Get
                Return Me.referencesField
            End Get
            Set
                Me.referencesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class AVCNameWithRefs
        
        Private avcNameField As AVCName
        
        Private nameRefListField As NameRefList
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property avcName() As AVCName
            Get
                Return Me.avcNameField
            End Get
            Set
                Me.avcNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nameRefList() As NameRefList
            Get
                Return Me.nameRefListField
            End Get
            Set
                Me.nameRefListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class StandardData
        
        Private avcNameWithRefsField As AVCNameWithRefs
        
        Private commentField As String
        
        Private commonNameWithRefsListField() As CommonNameWithRefs
        
        Private dataLinkField() As String
        
        Private familyField As String
        
        Private geographyField As Geography
        
        Private scrutinyField As Scrutiny
        
        Private synonymWithRefsListField() As SynonymWithRefs
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property avcNameWithRefs() As AVCNameWithRefs
            Get
                Return Me.avcNameWithRefsField
            End Get
            Set
                Me.avcNameWithRefsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property comment() As String
            Get
                Return Me.commentField
            End Get
            Set
                Me.commentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property commonNameWithRefsList() As CommonNameWithRefs()
            Get
                Return Me.commonNameWithRefsListField
            End Get
            Set
                Me.commonNameWithRefsListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property dataLink() As String()
            Get
                Return Me.dataLinkField
            End Get
            Set
                Me.dataLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property family() As String
            Get
                Return Me.familyField
            End Get
            Set
                Me.familyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property geography() As Geography
            Get
                Return Me.geographyField
            End Get
            Set
                Me.geographyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property scrutiny() As Scrutiny
            Get
                Return Me.scrutinyField
            End Get
            Set
                Me.scrutinyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property synonymWithRefsList() As SynonymWithRefs()
            Get
                Return Me.synonymWithRefsListField
            End Get
            Set
                Me.synonymWithRefsListField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class SpeciesName
        
        Private gsdIdentifierField As String
        
        Private identifierField As String
        
        Private nameWithAVCField As NameWithAVC
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property gsdIdentifier() As String
            Get
                Return Me.gsdIdentifierField
            End Get
            Set
                Me.gsdIdentifierField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property nameWithAVC() As NameWithAVC
            Get
                Return Me.nameWithAVCField
            End Get
            Set
                Me.nameWithAVCField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://webServiceCDM1_20.webServicePkg.spice2_0")>  _
    Partial Public Class Type1Results
        
        Private numberField As Integer
        
        Private speciesNamesField() As SpeciesName
        
        '''<remarks/>
        Public Property number() As Integer
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property speciesNames() As SpeciesName()
            Get
                Return Me.speciesNamesField
            End Get
            Set
                Me.speciesNamesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub webServiceTestCompletedEventHandler(ByVal sender As Object, ByVal e As webServiceTestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class webServiceTestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub satisfyType0RequestCompletedEventHandler(ByVal sender As Object, ByVal e As satisfyType0RequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class satisfyType0RequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub satisfyType1RequestCompletedEventHandler(ByVal sender As Object, ByVal e As satisfyType1RequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class satisfyType1RequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Type1Results
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Type1Results)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub type1WrapperTestCompletedEventHandler(ByVal sender As Object, ByVal e As type1WrapperTestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class type1WrapperTestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Type1Results
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Type1Results)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub satisfyType2RequestCompletedEventHandler(ByVal sender As Object, ByVal e As satisfyType2RequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class satisfyType2RequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StandardData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StandardData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub satisfyType3RequestCompletedEventHandler(ByVal sender As Object, ByVal e As satisfyType3RequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class satisfyType3RequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GSDInfo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GSDInfo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub satisfyType4RequestCompletedEventHandler(ByVal sender As Object, ByVal e As satisfyType4RequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class satisfyType4RequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Taxon()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Taxon())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub satisfyType5RequestCompletedEventHandler(ByVal sender As Object, ByVal e As satisfyType5RequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class satisfyType5RequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Taxon()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Taxon())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getHubIdentifiersCompletedEventHandler(ByVal sender As Object, ByVal e As getHubIdentifiersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getHubIdentifiersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getCrossMapMatchesCompletedEventHandler(ByVal sender As Object, ByVal e As getCrossMapMatchesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCrossMapMatchesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CrossMap
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CrossMap)
            End Get
        End Property
    End Class
End Namespace
