<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Default.aspx.vb" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Nomina Home</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:Label ID="Label1" runat="server" Font-Size="X-Large" Text="Nomina Registry"></asp:Label><br />
        <br />
        Providers<br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            CellPadding="4" DataKeyNames="ProviderRegistryID" DataSourceID="SqlDataSource1"
            ForeColor="#333333" GridLines="None" Width="550px">
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <Columns>
                <asp:BoundField DataField="ProviderRegistryID" HeaderText="ProviderRegistryID" InsertVisible="False"
                    ReadOnly="True" SortExpression="ProviderRegistryID" Visible="False" />
                <asp:ImageField DataImageUrlField="LogoUrl">
                </asp:ImageField>
                <asp:HyperLinkField DataNavigateUrlFields="ProviderRegistryId" DataNavigateUrlFormatString="providerform.aspx?provid={0}"
                    DataTextField="Title" HeaderText="Title" />
                <asp:BoundField DataField="EndpointURL" HeaderText="EndpointURL" SortExpression="EndpointURL" />
            </Columns>
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#999999" />
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:NominaConnectionString1 %>"
            DeleteCommand="deleteprovider" DeleteCommandType="StoredProcedure" SelectCommand="SELECT [Title], [LogoUrl], [ProviderRegistryID], [EndpointURL] FROM [ProviderRegistry]">
        </asp:SqlDataSource>
        <br />
        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="providerform.aspx">Create new provider</asp:HyperLink>
        &nbsp; &nbsp; &nbsp; &nbsp;<asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="uploadForm.aspx">Upload provider registry schema</asp:HyperLink><br />
    
    </div>
    </form>
</body>
</html>
