<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ProviderForm.aspx.vb" Inherits="ProviderForm" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:Label ID="Label3" runat="server" Font-Size="X-Large" Text="Nomina Registry"></asp:Label>&nbsp;
        <br />
        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="default.aspx">Home</asp:HyperLink>
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
        <asp:LinkButton ID="LinkButton1" runat="server">Get schema xml</asp:LinkButton><br />
        <br />
        <asp:Label ID="Label2" runat="server" Font-Names="Arial" Font-Size="Medium" Text="Provider details" Font-Bold="True"></asp:Label>&nbsp;
        <br />
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" DataKeyNames="ProviderRegistryID"
            DataSourceID="SqlDataSource3" Height="50px" Width="608px" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" AutoGenerateDeleteButton="True">
            <Fields>
                <asp:BoundField DataField="ProviderRegistryID" HeaderText="ProviderRegistryID" InsertVisible="False"
                    ReadOnly="True" SortExpression="ProviderRegistryID" Visible="False" />
                <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:BoundField DataField="LogoUrl" HeaderText="LogoUrl" SortExpression="LogoUrl" />
                <asp:BoundField DataField="Rights" HeaderText="Rights" SortExpression="Rights" />
                <asp:BoundField DataField="Citation" HeaderText="Citation" SortExpression="Citation" />
                <asp:BoundField DataField="MetadataURL" HeaderText="MetadataURL" SortExpression="MetadataURL" />
                <asp:BoundField DataField="EndpointURL" HeaderText="EndpointURL" SortExpression="EndpointURL" />
                <asp:BoundField DataField="DataURI" HeaderText="DataURI" SortExpression="DataURI" />
                <asp:BoundField DataField="DataURIType" HeaderText="DataURIType" SortExpression="DataURIType" />
                <asp:BoundField DataField="ResponseFormat" HeaderText="ResponseFormat" SortExpression="ResponseFormat" />
                <asp:BoundField DataField="RefreshPeriodHours" HeaderText="RefreshPeriodHours" SortExpression="RefreshPeriodHours" />
                <asp:BoundField DataField="TaxonomicScope" HeaderText="TaxonomicScope" SortExpression="TaxonomicScope" />
                <asp:BoundField DataField="GeospatialScopeWKT" HeaderText="GeospatialScopeWKT" SortExpression="GeospatialScopeWKT" />
                <asp:BoundField DataField="CreateTimestamp" HeaderText="CreateTimestamp" SortExpression="CreateTimestamp" />
                <asp:BoundField DataField="ModifiedTimestamp" HeaderText="ModifiedTimestamp" SortExpression="ModifiedTimestamp" />
            </Fields>
            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="Gainsboro" />
        </asp:DetailsView>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:NominaConnectionString1 %>"
            SelectCommand="SELECT * FROM [ProviderRegistry]" FilterExpression="ProviderRegistryId={0}" InsertCommand="insertupdateprovider" InsertCommandType="StoredProcedure" UpdateCommand="insertupdateprovider" UpdateCommandType="StoredProcedure">
            <FilterParameters>
                <asp:QueryStringParameter DefaultValue="" Name="newparameter" QueryStringField="provid" />
            </FilterParameters>
            <InsertParameters>
                <asp:Parameter Direction="ReturnValue" Name="RETURN_VALUE" Type="Int32" />
                <asp:FormParameter FormField="ProviderRegistryId" Name="providerRegistryId" Type="Int32" />
                <asp:FormParameter DefaultValue="" FormField="Title" Name="title" Type="String" />
                <asp:FormParameter DefaultValue="" FormField="Description" Name="description" Type="String" />
                <asp:FormParameter FormField="MetadataUrl" Name="metadataUrl" Type="String" />
                <asp:FormParameter FormField="EndpointUrl" Name="endpointUrl" Type="String" />
                <asp:FormParameter FormField="LogoUrl" Name="LogoUrl" Type="String" />
                <asp:FormParameter FormField="Rights" Name="Rights" Type="String" />
                <asp:FormParameter FormField="Citation" Name="Citation" Type="String" />
                <asp:FormParameter FormField="DataURI" Name="DataURI" Type="String" />
                <asp:FormParameter FormField="DataURIType" Name="DataURIType" Type="String" />
                <asp:FormParameter FormField="ResponseFormat" Name="ResponseFormat" Type="String" />
                <asp:FormParameter FormField="RefreshPeriodHours" Name="RefreshPeriodHours" Type="Int32" />
                <asp:FormParameter FormField="TaxonomicScope" Name="TaxonomicScope" Type="String" />
                <asp:FormParameter FormField="GeospatialScopeWKT" Name="GeospatialScopeWKT" Type="String" />
                <asp:FormParameter FormField="CreateTimestamp" Name="CreateTimestamp" Type="DateTime" />
                <asp:FormParameter FormField="ModifiedTimestamp" Name="ModifiedTimestamp" Type="DateTime" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Direction="ReturnValue" Name="RETURN_VALUE" Type="Int32" />
                <asp:FormParameter FormField="ProviderRegistryId" Name="providerRegistryId" Type="Int32" />
                <asp:FormParameter FormField="Title" Name="title" Type="String" />
                <asp:FormParameter FormField="Description" Name="description" Type="String" />
                <asp:FormParameter FormField="MetadataUrl" Name="metadataUrl" Type="String" />
                <asp:FormParameter FormField="EndpointUrl" Name="endpointUrl" Type="String" />
                <asp:FormParameter FormField="LogoUrl" Name="LogoUrl" Type="String" />
                <asp:FormParameter FormField="Rights" Name="Rights" Type="String" />
                <asp:FormParameter DefaultValue="" FormField="Citation" Name="Citation" Type="String" />
                <asp:FormParameter FormField="DataURI" Name="DataURI" Type="String" />
                <asp:FormParameter FormField="DataURIType" Name="DataURIType" Type="String" />
                <asp:FormParameter FormField="ResponseFormat" Name="ResponseFormat" Type="String" />
                <asp:FormParameter FormField="RefreshPeriodHours" Name="RefreshPeriodHours" Type="Int32" />
                <asp:FormParameter FormField="TaxonomicScope" Name="TaxonomicScope" Type="String" />
                <asp:FormParameter FormField="GeospatialScopeWKT" Name="GeospatialScopeWKT" Type="String" />
                <asp:FormParameter FormField="CreateTimestamp" Name="CreateTimestamp" Type="DateTime" />
                <asp:FormParameter FormField="ModifiedTimestamp" Name="ModifiedTimestamp" Type="DateTime" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <asp:Label ID="Label4" runat="server" Font-Bold="True" Font-Names="Arial" Font-Size="Medium"
            Text="Accession Rules"></asp:Label><br />
        <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource4"
            EmptyDataText="There are no data records to display." ForeColor="#333333" GridLines="None"
            Width="600px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <Columns>
                <asp:BoundField DataField="AccessionTypeId" HeaderText="id" Visible="False" />
                <asp:BoundField DataField="Type" HeaderText="Accession Type" />
                <asp:BoundField DataField="IsAllowed" HeaderText="Is Allowed" />
            </Columns>
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#999999" />
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:NominaConnectionString1 %>"
            DeleteCommand="DELETE FROM [EntityRole] WHERE [EntityRoleID] = @EntityRoleID"
            FilterExpression="ProviderRegistryId={0}" InsertCommand="INSERT INTO [EntityRole] ([Role]) VALUES (@Role)"
            ProviderName="<%$ ConnectionStrings:NominaConnectionString1.ProviderName %>"
            SelectCommand="SELECT ProviderRegistryId, AccessionTypeId, Type, IsAllowed FROM vwAccRules" UpdateCommand="UPDATE [EntityRole] SET [Role] = @Role WHERE [EntityRoleID] = @EntityRoleID">
            <DeleteParameters>
                <asp:Parameter Name="EntityRoleID" Type="Int32" />
            </DeleteParameters>
            <FilterParameters>
                <asp:QueryStringParameter DefaultValue="null" Name="newparameter" QueryStringField="provid" />
            </FilterParameters>
            <UpdateParameters>
                <asp:Parameter Name="Role" Type="String" />
                <asp:Parameter Name="EntityRoleID" Type="Int32" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="Role" Type="String" />
            </InsertParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        <asp:Label ID="Label1" runat="server" Font-Names="Arial" Font-Size="Medium" Text="Provider Entities" Font-Bold="True"></asp:Label>
        <br />
        Entity &nbsp; &nbsp;&nbsp;
        <asp:GridView ID="GridView2" runat="server" AllowSorting="True" AutoGenerateColumns="False"
            DataKeyNames="EntityId" DataSourceID="SqlDataSource2" EmptyDataText="There are no data records to display."
            Width="517px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" DataMember="DefaultView" ForeColor="#333333" GridLines="None">
            <Columns>
                <asp:BoundField DataField="EntityId" HeaderText="EntityId" SortExpression="EntityId"
                    Visible="False" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Identifier" HeaderText="Identifier" />
                <asp:BoundField DataField="Acronym" HeaderText="Acronym" />
            </Columns>
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#999999" />
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:NominaConnectionString1 %>"
            ProviderName="<%$ ConnectionStrings:NominaConnectionString1.ProviderName %>"
            SelectCommand="SELECT ProviderRegistryId, [EntityId], [Name], [Identifier], [Acronym] FROM [vwProviderEntities]" DeleteCommand="delete c&#13;&#10;from contact c&#13;&#10;inner join entitycontact ec on ec.contactid = c.contactid&#13;&#10;where ec.entityid = {0};&#13;&#10;delete entitycontact where entityid = {0};&#13;&#10;delete entity where entityid = {0}" UpdateCommand="update entity&#13;&#10;set name = {0}" FilterExpression="ProviderRegistryId={0}" InsertCommand="insertupdateentity" InsertCommandType="StoredProcedure">
            <DeleteParameters>
                <asp:ControlParameter ControlID="GridView2" Name="newparameter" PropertyName="SelectedValue" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="GridView1" Name="newparameter" PropertyName="SelectedValue" />
            </UpdateParameters>
            <FilterParameters>
                <asp:QueryStringParameter DefaultValue="null" Name="newparameter" QueryStringField="provid" />
            </FilterParameters>
            <InsertParameters>
                <asp:Parameter Direction="ReturnValue" Name="RETURN_VALUE" Type="Int32" />
                <asp:FormParameter FormField="ProviderRegistryId" Name="providerRegistryId" Type="Int32" />
                <asp:Parameter DefaultValue="1" Name="roleId" Type="Int32" />
                <asp:ControlParameter ControlID="GridView2" DefaultValue="" Name="EntityID" PropertyName="SelectedValue"
                    Type="Int32" />
                <asp:FormParameter FormField="Name" Name="Name" Type="String" />
                <asp:FormParameter FormField="Identifier" Name="Identifier" Type="String" />
                <asp:FormParameter FormField="Acronym" Name="Acronym" Type="String" />
                <asp:Parameter Name="LogoURL" Type="String" />
                <asp:Parameter Name="Description" Type="String" />
                <asp:Parameter Name="Address" Type="String" />
                <asp:Parameter Name="DecimalLatitude" Type="Double" />
                <asp:Parameter Name="DecimalLongitude" Type="Double" />
            </InsertParameters>
        </asp:SqlDataSource>
        <br />
        Contacts &nbsp; &nbsp; &nbsp;
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False"
            DataSourceID="SqlDataSource1" EmptyDataText="There are no data records to display."
            Width="522px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="ContactId" DataMember="DefaultView" ForeColor="#333333" GridLines="None">
            <Columns>
                <asp:BoundField DataField="ContactId" HeaderText="ContactId" SortExpression="ContactId"
                    Visible="False" />
                <asp:BoundField DataField="Role" HeaderText="Role" />
                <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                <asp:BoundField DataField="FullName" HeaderText="Full name" />
                <asp:BoundField DataField="Email" HeaderText="Email" />
            </Columns>
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#999999" />
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:NominaConnectionString1 %>"
            FilterExpression="EntityId={0}" ProviderName="<%$ ConnectionStrings:NominaConnectionString1.ProviderName %>"
            SelectCommand="SELECT  ContactId, EntityId, Role, Title, Fullname, Email FROM [vwContacts]" DeleteCommand="delete contact where contactid = {0}">
            <FilterParameters>
                <asp:ControlParameter ControlID="GridView2" Name="newparameter" PropertyName="SelectedValue" DefaultValue="null" />
            </FilterParameters>
            <DeleteParameters>
                <asp:ControlParameter ControlID="GridView1" Name="newparameter" PropertyName="SelectedValue" />
            </DeleteParameters>
        </asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
