
Public Class DwcTaxon
    Public recordModifiedDate As DateTime = DateTime.MinValue
    Public recordCreator As String = ""

    Public taxonID As String = ""
    Public scientificNameID As String = ""
    Public scientificName As String = ""
    Public acceptedNameUsageID As String = ""
    Public acceptedNameUsage As String = ""
    Public parentNameUsageID As String = ""
    Public parentNameUsage As String = ""
    Public originalNameUsageID As String = ""
    Public originalNameUsage As String = ""
    Public nameAcccordingToID As String = ""
    Public nameAcccordingTo As String = ""
    Public namePublishedInID As String = ""
    Public namePublishedIn As String = ""
    Public taxonConceptID As String = ""
    Public higherClassification As String = ""
    Public kingdom As String = ""
    Public phylum As String = ""
    Public [class] As String = ""
    Public order As String = ""
    Public family As String = ""
    Public genus As String = ""
    Public subgenus As String = ""
    Public specificEpithet As String = ""
    Public infraspecificEpithet As String = ""
    Public taxonRank As String = ""
    Public verbatimTaxonRank As String = ""
    Public scientificNameAuthorship As String = ""
    Public vernacularName As String = ""
    Public nomenclaturalCode As String = ""
    Public taxonomicStatus As String = ""
    Public nomenclaturalStatus As String = ""
    Public taxonRemarks As String = ""

End Class
